version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    image: node:18
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "npm install -g firebase-tools && firebase emulators:start --only functions,firestore"
    ports:
      - "5001:5001" # Firebase Functions
      - "8085:8085" # Firestore
      - "4000:4000" # Emulator UI
